version: '3'
services:
  strapi:
    image: strapi/strapi
    restart: unless-stopped
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: 5432
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./backend:/srv/app
    ports:
      - '1337:1337'

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - strapidata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  nextjs:
    image: tairise/nextjs
    environment: 
      TEMPLATE: default
      API_URL: ${BACKEND_URL:-http://strapi:1337}
    volumes:
      - ./frontend:/srv/app
    ports:
        - '3000:3000'

volumes:
  strapidata: